version: "3.3"

services:
  _SERVICE_NAME_:
    image: _AWS_ACCOUNT_ID_.dkr.ecr.us-east-1.amazonaws.com/_ECR_IMG_:_CI_COMMIT_SHORT_SHA_
    environment:
      - API_URL=_API_URL_
      - ACCESS_URL=_ACCESS_URL_
    networks:
      - cntlog
    volumes:
      - /etc/localtime:/etc/localtime
    deploy:
      placement:
        constraints:
          - node.role == _SWARM_NODE_
      resources:
        limits:
          memory: 8G
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
        window: 300s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers._SERVICE_NAME_.rule=Host(`_ACCESS_URL_`)"
        - "traefik.http.routers._SERVICE_NAME_.entrypoints=web"
        - "traefik.http.services._SERVICE_NAME_.loadbalancer.server.port=3000" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers._SERVICE_NAME_-secured.rule=Host(`_ACCESS_URL_`)"
        - "traefik.http.routers._SERVICE_NAME_-secured.entrypoints=web-secured"
        - "traefik.http.routers._SERVICE_NAME_-secured.tls.certresolver=mytlschallenge"
        - "traefik.http.routers._SERVICE_NAME_.middlewares=redirect@file"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://log.thorpe.com.br:12201"
        tag: "_SERVICE_NAME_"

networks:
  cntlog:
    driver: overlay
