version: '3'

services:
  fisacorp-front:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fisacorp-front
    volumes:
      - ./:/app
    environment:
      TZ: 'America/Sao_Paulo'
    ports:
      - '3000:3000'
